name: Run tests
on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'
      - '**/*.zig'
      - 'deps/**'
      - '.github/**'
  pull_request:
    branches: [main, zig-master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Zig setup
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Run all tests
        run: zig build test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Check formatting
        run: zig fmt --check .
